# Book settings
title: Ames, Iowa Housing Dataset
author: Chirag Limbachia
copyright: "2020"
logo: "logo.png"

execute:
  exclude_patterns:
    - "04-*"

latex:
  latex_documents:
    targetname: book.tex

###########################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

##########################################################################
# Launch button settings
repository:
  url: https://github.com/limbachia/House-Price-Prediction
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
